/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EasyCode.BlocosFuncionais;

import EasyCode.Pais.Bloco;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Miguel Oliveira
 */
public class BFEscrevaTXT extends Bloco {
 private final Dimension dimensoes = new Dimension(294,21);
    /**
     * Creates new form BFEscreva
     */
    public BFEscrevaTXT() {
        super("EscrevaTxt","Funcao Escreva");
        initComponents();
        setSize(dimensoes);
    }
    public BFEscrevaTXT(String condicao) {
        super("EscrevaTxt","Funcao Escreva");
        initComponents();
        jTextField1.setText(condicao);
        setSize(dimensoes);
    }
      public Dimension getDimensoes() {
        return dimensoes;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Escreva");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 70, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 0, 210, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JPanel componentes () {
        return this.jPanel1;
    }
    public String getCondicao () {
        return jTextField1.getText();
    }
    public void setCondicao (String txt) {
       jTextField1.setText(txt);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
