/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EasyCode.BlocosEstruturais;

import EasyCode.Pais.Bloco;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Endy Takano
 */
public class BEscolhaCaso extends Bloco {
    /**
     * Creates new form BEscolhaCase
     */
    private final Dimension dimensoes = new Dimension(224,21);
    public BEscolhaCaso() {
        super("Caso","Estrutura Caso");
        initComponents();
        setSize(dimensoes);
    }
    public BEscolhaCaso(String condicao) {
        super("Caso","Estrutura caso, de escolha");
        initComponents();
        jTextField1.setText(condicao);
        
        setSize(dimensoes);
    }
 public Dimension getDimensoes() {
        return dimensoes;
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(400, 20));

        jPanel1.setBackground(new java.awt.Color(198, 195, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Caso");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 0, 40, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(58, 1, 147, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

 @Override
    public javax.swing.JPanel componentes () {
        return this.jPanel1;
    }
    
     public String getCondicao () {
        return jTextField1.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
