/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EasyCode.BlocosArduino;


import EasyCode.Main;
import EasyCode.Pais.Bloco;
import EasyCode.Pais.Variavel;
import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author Endy Takano
 */
public class BADigitalRead extends Bloco {

    private final Dimension dimensoes = new Dimension(331, 20);
    private String nome;
    /**
     * Creates new form BEpara
     */
    public BADigitalRead(){
        super("DigitalRead", "Estrutura DigitalRead");
        initComponents();
              JCBvariaveis.removeAllItems();
        for (Variavel var : Main.listaVar) {
            JCBvariaveis.addItem(var.getVar());
        }
        setVisible(true);
        setSize(dimensoes);

    }

    public BADigitalRead(int pino, String tipo, ArrayList<Variavel> listaVar) {
        super("DigitalRead", "Estrutura DigitalRead");
        initComponents();
        jSpinner1.setValue(pino);
     JCBvariaveis.removeAllItems();
        for (Variavel var : listaVar) {
            JCBvariaveis.addItem(var.getVar());
        }
        setVisible(true);
        setSize(dimensoes);

    }
   public String getCondicao(){
        return JCBvariaveis.getItemAt(JCBvariaveis.getSelectedIndex());
    }
    public Dimension getDimensoes() {
        return dimensoes;
    }

    @Override
    public javax.swing.JPanel componentes() {
        return this.JP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        JCBvariaveis = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(400, 20));

        JP.setBackground(new java.awt.Color(0, 153, 153));
        JP.setPreferredSize(new java.awt.Dimension(400, 24));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("= Entrada Digital");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        JCBvariaveis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        JCBvariaveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBvariaveisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPLayout = new javax.swing.GroupLayout(JP);
        JP.setLayout(JPLayout);
        JPLayout.setHorizontalGroup(
            JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(JCBvariaveis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPLayout.setVerticalGroup(
            JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(JCBvariaveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(JP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JCBvariaveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBvariaveisActionPerformed
        for (Variavel aux : Main.listaVar) {
            if (JCBvariaveis.getItemAt(JCBvariaveis.getSelectedIndex()) == aux.getVar()) {
                nome = aux.getVar();
            }
        }
    }//GEN-LAST:event_JCBvariaveisActionPerformed

    @Override
    public String getPino() {
        return jSpinner1.getValue().toString();
    }
    
    @Override
    public String getVar() {
        return nome;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCBvariaveis;
    private javax.swing.JPanel JP;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
